Add man page generation and release packaging
Generate git-b.1 with clap_mangen from a shared git-b-cli crate. Release
tarballs and the Homebrew formula now ship share/man/man1/git-b.1.

Co-authored-by: Cursor <cursoragent@cursor.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -13,25 +13,38 @@ mac_intel_tar="$name-v$version-$mac_intel.tar.gz"
 mac_silicon_tar="$name-v$version-$mac_silicon.tar.gz"
 linux_intel_tar="$name-v$version-$linux_intel.tar.gz"
 
+package_tarball() {
+  local target="$1"
+  local tarball="$2"
+  local staging
+  staging=$(mktemp -d)
+
+  mkdir -p "$staging/share/man/man1"
+  cp "target/$target/release/$name" "$staging/"
+  cp "man/git-b.1" "$staging/share/man/man1/"
+
+  tar -czvf "$tarball" -C "$staging" .
+  rm -rf "$staging"
+}
+
+# Release build runs build.rs, which writes man/git-b.1
 cargo build --target=$mac_intel --release
 cargo build --target=$mac_silicon --release
-CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc cargo build --target=$linux_intel --release
+CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc \
+  cargo build --target=$linux_intel --release
 
-cd target/$mac_silicon/release
-tar -czvf "$mac_silicon_tar" $name
+if [[ ! -f man/git-b.1 ]]; then
+  echo "error: man/git-b.1 not found (expected from build.rs)" >&2
+  exit 1
+fi
+
+package_tarball "$mac_silicon" "$mac_silicon_tar"
 silicon_sha=$(shasum -a 256 "$mac_silicon_tar" | cut -d ' ' -f 1)
-mv "$mac_silicon_tar" ../../../"$mac_silicon_tar"
 
-cd ../../$mac_intel/release
-tar -czvf "$mac_intel_tar" $name
+package_tarball "$mac_intel" "$mac_intel_tar"
 intel_sha=$(shasum -a 256 "$mac_intel_tar" | cut -d ' ' -f 1)
-mv "$mac_intel_tar" ../../../"$mac_intel_tar"
 
-cd ../../$linux_intel/release
-tar -czvf "$linux_intel_tar" $name
-mv "$linux_intel_tar" ../../../"$linux_intel_tar"
-
-cd ../../../
+package_tarball "$linux_intel" "$linux_intel_tar"
 
 sed -i '' -e "s|X86_64_SHA\ \=.*|X86_64_SHA = '$intel_sha'|" Formula/git-b.rb
 sed -i '' -e "s|AARCH64_SHA\ \=.*|AARCH64_SHA = '$silicon_sha'|" Formula/git-b.rb
